name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: macos-26

    steps:
    - uses: actions/checkout@v6
    - run: swift test -v

  build-macos:
    runs-on: macos-26

    steps:
    - uses: actions/checkout@v6
    - run: xcodebuild -scheme mpw-swift -configuration Debug CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY=""
